---
language: python
sudo: required
dist: trusty
cache: pip
env:
  global:
    - fast_finish: true
    - MAKEFLAGS="-j 2"
matrix:
  include:
    - env: IMAGE="debian/9"
    - env: IMAGE="debian/8"
    - env: IMAGE="ubuntu/16.04"
    - env: IMAGE="ubuntu/14.04"
    - env: IMAGE="centos/7" COMMAND="/usr/lib/systemd/systemd"
    - env: IMAGE="centos/6" COMMAND="/sbin/init"
    - env: IMAGE="fedora/27"
    - env: IMAGE="fedora/26" COMMAND="/sbin/init"
#    - env: IMAGE="ubuntu/16.04"
#      env: COMMAND="/usr/lib/systemd/systemd"
#      env: ANSIBLE_VERSION='ansible>=2.2.0,<2.3.0' #2.2.x security only
#    - env: IMAGE="ubuntu/16.04"
#      env: COMMAND="/usr/lib/systemd/systemd"
#      env: ANSIBLE_VERSION='ansible>=2.3.0,<2.4.0' #2.3.x bugs and security
#    - env: IMAGE="ubuntu/16.04"
#      env: COMMAND="/usr/lib/systemd/systemd"
#      env: ANSIBLE_VERSION='ansible>=2.4.0,<2.5.0' #2.4.x bugs and security
#    - env: IMAGE="ubuntu/16.04"
#      env: COMMAND="/usr/lib/systemd/systemd"
#      env: ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel' #2.5 DEVEL
#    - env: IMAGE="ubuntu/16.04"
#      env: COMMAND="/usr/lib/systemd/systemd"
#      env: ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3' #Python3

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - if [ "$ANSIBLE_VERSION" ]; then pip install $ANSIBLE_VERSION; else pip install ansible; fi
  - pip install molecule

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/