---
language: python
sudo: required
dist: trusty
cache:
  pip: true
env:
  global:
    - fast_finish: true
    - MAKEFLAGS="-j 2"
    - COMMAND=bash -c \"while true; do sleep 10000; done\"
  matrix:
    - ANSIBLE_VERSION='ansible>=2.2.0,<2.3.0' #2.2.x security only
    - ANSIBLE_VERSION='ansible>=2.3.0,<2.4.0' #2.3.x bugs and security
    - ANSIBLE_VERSION='ansible>=2.4.0,<2.5.0' #2.4.x bugs and security
    - ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel' #2.5 DEVEL
    - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3' #Python3

matrix:
  allow_failures:
    - ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel' #2.5 DEVEL
    - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3' #Python3

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install --only-upgrade docker-ce -y

install:
  - if [ "$ANSIBLE_VERSION" ]; then pip install $ANSIBLE_VERSION; else pip install ansible; fi
  - pip install molecule docker-py

script:
  - ansible --version
  - molecule test

notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
