---
- include: plex.yml

- include: tautulli.yml
  when: tautulli_install

- include: plexupdate.yml
  when: plexupdate_install

#- include: configure-firewalld.yml
#  when: ansible_os_family == "RedHat"
