---
- name: PLEX | Install git
  package:
    name: git
    state: present

- name: PLEXPY | Create user
  group:
    name: "{{ plexpy_group }}"
    state: present

- name: PLEXPY | Create user
  user:
    name: "{{ plexpy_user }}"
    group: "{{ plexpy_group }}"
    createhome: no

- name: PLEXPY | Clone Plexpy repo
  git:
    repo: https://github.com/JonnyWong16/plexpy
    dest: "{{ plexpy_install_location }}"

- name: PLEXPY | Set permissions
  file:
    path: "{{ plexpy_install_location }}"
    owner: "{{ plexpy_user }}"
    group: "{{ plexpy_group }}"
    recurse: yes

- block:
    - name: PLEXPY | Move init script for using systemd
      template:
        src: plexpy/init.systemd.tpl
        dest: /lib/systemd/system/plexpy.service
        owner: root
        group: root
        mode: 0644

    - name: PLEXPY | Autostart Plexpy and start service
      systemd:
        name: plexpy
        state: started
        enabled: yes
        daemon_reload: yes

  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version < '15.10')

- block:
    - name: PLEXPY | Move init script for older ubuntu versions
      file:
        src: "{{ plexpy_install_location }}/init-scripts/init.ubuntu"
        dest: /etc/init.d/plexpy
        owner: root
        group: root
        mode: 0744
        state: link

    - name: PLEXPY | Set defaults in file
      template:
        src: plexpy/ubuntu-plexpy.tpl
        dest: /etc/default/plexpy

    - name: PLEXPY | Autostart Plexpy and start service
      service:
        name: plexpy
        state: started
        enabled: yes

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version < '15.10'