---
- name: Install git
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - git

- name: Clone plexupdate repository
  git:
    repo: https://github.com/mrworf/plexupdate.git
    dest: "{{ plexupdate_install_location }}"

- name: Create desired config
  template:
    src: plexupdate/plexupdate.conf.jinja2
    dest: "{{ plexupdate_config_location }}"

- name: Create cron config
  template:
    src: plexupdate/plexupdate.cron.conf.jinja2
    dest: "/etc/plexupdate.cron.conf"

- name: Create cron job
  file:
    src: "{{ plexupdate_install_location }}/extras/cronwrapper"
    dest: "{{ plexupdate_cronwrapper }}"
    state: link
  when: plexupdate_autoinstall or plexupdate_autoupdate