---
- name: PLEXUPDATE | Install git
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - git

- name: PLEXUPDATE | Copy plexupdate install script
  template:
    src: plexupdate/installer.sh.tpl
    dest: /root/installer.sh

- name: PLEXUPDATE | Install plexupdate
  command: sh /root/installer.sh

- name: PLEXUPDATE | Cleanup install script
  file:
    path: /root/installer.sh
    state: absent